export default {
  GET_LOCATION_PERMISSION: 'GET_LOCATION_PERMISSION',
  SET_LOCATION_PERMISSION: 'SET_LOCATION_PERMISSION',
  GETTING_CURRENT_LOCATION: 'GETTING_CURRENT_LOCATION',
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_INPUT: 'GET_INPUT',
  TOGGLE_SEARCH_RESULT: 'TOGGLE_SEARCH_RESULT',
  GET_LOCATION_PREDICTIONS: 'GET_LOCATION_PREDICTIONS',
  GET_SELECTED_ADDRESS: 'GET_SELECTED_ADDRESS',
  GET_DISTANCE_MATRIX: 'GET_DISTANCE_MATRIX',
  UPDATE_CENTER_MARKER: 'UPDATE_CENTER_MARKER',
  HANDLE_CENTRE_COORD: 'HANDLE_CENTRE_COORD',
  DISPLAY_NEARBY_PARKING_SPOTS: 'DISPLAY_NEARBY_PARKING_SPOTS',
};