export default {
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_INPUT: 'GET_INPUT',
  TOGGLE_SEARCH_RESULT: 'TOGGLE_SEARCH_RESULT',
  GET_LOCATION_PREDICTIONS: 'GET_LOCATION_PREDICTIONS',
  GET_SELECTED_ADDRESS: 'GET_SELECTED_ADDRESS'
};