# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'reactNativePractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativePractice
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'reactNativePracticeTests' do
    # inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativePractice-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativePractice-tvOS

  target 'reactNativePractice-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  end

end
