# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativePractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativePractice
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'reactNativePractice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNativePracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativePractice-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativePractice-tvOS

  target 'reactNativePractice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
